### ISSUE TITLE
Lens links not working if nova path === '/'

### ISSUE THREAD

**Issue by benedict-w** [sietse85/nova-button#10]
I'm trying to setup a link to a Lens which displays a report on the index of a `Subscriber` Resource, as follows:

```
    Button::make('Report')
        ->lens(\App\Nova\Subscriber::class, 'subscriber-offers-report')
        ->style('grey-link')

```
Where my resource class is `\App\Nova\Subscriber` and the Lens $key is `'subscriber-offers-report'`. This correctly shows the Report button link, but if I click the button, it pauses and then shows "Failed" and doesn't navigate to the Lens as I had hoped.

Am I doing something wrong?

**Comment by sietse85** [comment]
@benedict-w  fixed in v1.0.16

**Comment by benedict-w** [comment]
@sietse85 Thanks for the quick response!

I still have an issue though, sorry! The link used is wrong looks like it should be relative?

`GET http://resources/subscribers/lens/subscriber-offers-report net::ERR_NAME_NOT_RESOLVED`

Console output:

<img width="997" alt="Screenshot 2022-07-07 at 19 37 07" src="https://user-images.githubusercontent.com/1303610/177845382-ba33d816-ec22-4b9c-98f7-d9a86866a61e.png">

**Comment by sietse85** [comment]
@benedict-w did you set your base path variable for nova? i cannot reproduce this locally i test all (index/detail/edit/create/lens) and they do work. Also try clearing your javascript cache from Nova.

**Comment by benedict-w** [comment]
@sietse85 My `Nova.appConfig.base` is set to '/' which is correct as Nova is running on mine.

I've cleared all the caches and it seems to be running the latest code in the browser.

**Comment by sietse85** [comment]
@benedict-w  weird i shall take a deeper look into it then, i cannot reproduce this locally and have no idea whats causing it not to work in your project.

**Comment by sietse85** [comment]
@benedict-w  whats the value of your `APP_URL` variable in .env file?

**Comment by benedict-w** [comment]
> @benedict-w whats the value of your `APP_URL` variable in .env file?

the test URL of my project

**Comment by sietse85** [comment]
@benedict-w  i have no idea whats going on in your project, i can't reproduce this at all

**Comment by benedict-w** [comment]
Thanks very much for trying! I’m on holiday for a week from tomorrow but will try and look into it when I’m back.

**Comment by sietse85** [comment]
@benedict-w  sure thanks, i must be some setting thats not correct somewhere, last question i have is how do you access nova its via `/nova` isnt it?

**Comment by benedict-w** [comment]
No it’s in the root, i.e. 'path' => '/',

**Comment by sietse85** [comment]
Well okay so the main issue obviously is the domain name isnt included in the url looking at your inspector, locally for me it just does this fine for me (automaticly) and i cant think of a reason why it would not add the domain name in your case. Let me know if you find anything.

**Comment by benedict-w** [comment]
@sietse85 The problem seems to be that because my Nova `'path' => '/'` when Nova Button tries to build the base URL [here](https://github.com/sietse85/nova-button/blob/master/resources/js/components/NovaButton.vue#L132) it's getting an extra slash `/` at the start, which for some reason is causing Inertia to treat the path as absolute and not relative. (Without the slash it works). I could create a pull request to remove duplicate slashes from the start but there's probably a more intelligent way of getting it right!

**Comment by benedict-w** [comment]
@sietse85 If you look in Nova's `resources/js/uril/url.js` they are doing exactly this!

```
  if (base == '/' && path.startsWith('/')) {
      base = ''
  }
```

Have created a pull request in bc8e6bc
